### ISSUE TITLE
Can't log in with google accounts

### ISSUE THREAD

**Issue by Inkln** [catalyst-team/alchemy#2]
This error occurs often but not always, I can't find regularity and repeat all steps to reproduce it well.

In Google Chrome 79.0.3945.130
![image](https://user-images.githubusercontent.com/16538765/73171391-afecc280-4111-11ea-8461-e4ee66ad6865.png)
And Mozilla Firefox 72.0.1
![image](https://user-images.githubusercontent.com/16538765/73171471-da3e8000-4111-11ea-8e4c-6f1f8339c794.png)

Checked with two accounts ...@gmail.com and ...@phystech.edu,

**Comment by dkuryakin** [comment]
@Avi2011class thanks for reporting!

I've add some dummy logging to console on Login event. What do you see in console now in case of bug?

**Comment by Scitator** [comment]
fixed :)
