### ISSUE TITLE
No records shown after update

### ISSUE THREAD

**Issue by Arquestro** [catalyst-team/alchemy#3]
Have been using AlchemyRunner from version 0.0.1.
My guess is that some headers are empty compared to latest(unpublished) Alchemy version.

**Comment by dkuryakin** [comment]
@Arquestro thanks for reporting! You are right. Actually new version of logger was available in master scince yesterday release. But we forgot to publish it as a new release & push it to pypi.

Now you can use this command:
`pip3 install https://github.com/catalyst-team/alchemy/archive/v0.0.2.zip`

Also, we will push it to pip asap.

**Comment by dkuryakin** [comment]
@Arquestro check alchemy-catalyst==20.1.1
