### ISSUE TITLE
Hosting Alchemy.host locally?

### ISSUE THREAD

**Issue by MickaelCormier** [catalyst-team/alchemy#6]
Hi, Thanks for the great work!

Would it be possible to opensource the monitoring website in order to host it locally?

**Comment by Arquestro** [comment]
Main reason not to open source monitoring site are the security matters, imo.

**Comment by Arquestro** [comment]
As far as I know, Alchemy will be more than monitoring service in near future. Therefore I don't feel that it is a good idea to give away whole product solution.

**Comment by Arquestro** [comment]
@Scitator and @dkuryakin will answer more clearly on this one. :)

**Comment by dkuryakin** [comment]
@MickaelCormier just like @Arquestro said. It's possible in far future, but not right now.
